open System
#load "Manipulation.fs"
#load "HelloWorld.fs"
#load "BindStuff.fs"
#load "DoFunctions.fs"
#load "DoMath.fs"
#load "StringStuff.fs"
#load "LoopStuff.fs"
#load "ConditionalStuff.fs"
#load "ListStuff.fs"
#load "EnumStuff.fs"
#load "OptionStuff.fs"
#load "TupleStuff.fs"
#load "RecordStuff.fs"
#load "SequenceStuff.fs"
#load "MapStuff.fs"
#load "GenericStuff.fs"
#load "ExceptionStuff.fs"
#load "StructStuff.fs"

open Manipulation
open HelloWorld
open BindStuff
open DoFunctions
open DoMath
open StringStuff
open LoopStuff
open ConditionalStuff
open ListStuff
open EnumStuff
open OptionStuff
open TupleStuff
open RecordStuff
open SequenceStuff
open MapStuff
open GenericStuff
open ExceptionStuff
open StructStuff

// StringManipulation.dynamicSpacing()
// NumberManipulation.FloatLimitation()
// BindValues.mutableValue()
// BindValues.referenceCell()
// Functions.DisplaySum()
// Functions.RunFactorial()
// Functions.DoubleList()
// Functions.MultiNum()
// Maths.Basic()
// Strings.DoStuff()
// //Loops.WhileLoops()
// Loops.ForLoops()
// Conditionals.IfStatement()
// Lists.ListLiteral()
// Enums.Run()
// Options.runMe()
// Tuples.runMe()
// Records.runMe()
// Sequences.runMe()
// Maps.runMe()
// Generics.runMe()
// Exceptions.runMe()
Structs.runMe()

// Question.AskName()
